# Generated by Django 2.0.1 on 2018-01-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180119_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteurl',
            name='email',
            field=models.CharField(default=None, max_length=128, verbose_name='Email'),
        ),
    ]
