# Generated by Django 2.0.1 on 2018-01-19 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_inviteurl_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={'verbose_name': 'Зарегестрированный по приглашению', 'verbose_name_plural': 'Зарегестрированные по приглашениям'},
        ),
        migrations.AlterField(
            model_name='invite',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invite_from', to=settings.AUTH_USER_MODEL, verbose_name='Приглашение от'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='user_invite',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invite_to', to=settings.AUTH_USER_MODEL, verbose_name='Пришлашение кому'),
        ),
    ]
