# Generated by Django 2.0.1 on 2018-01-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180119_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='url',
            field=models.CharField(default=None, max_length=128, verbose_name='Инвайт'),
        ),
    ]
