# Generated by Django 2.0.1 on 2018-01-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_invite_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteurl',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
