# Generated by Django 2.0.1 on 2018-01-19 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_inviteurl_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='user_invite',
        ),
        migrations.AddField(
            model_name='inviteurl',
            name='user_invite',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_to', to=settings.AUTH_USER_MODEL, verbose_name='Пришлашение кому'),
        ),
        migrations.AlterField(
            model_name='inviteurl',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invite_from', to=settings.AUTH_USER_MODEL, verbose_name='Приглашение от'),
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
